Repository crawler-commons/url-frontier, pull requests merged in 2024-09, with the labels that each got.

#97 adds dependabot
  .github/dependabot.yml
Labels: enhancement

#99 Fix #87, similar behaviour re-blocking whether specitying a key or not
  service/src/main/java/crawlercommons/urlfrontier/service/AbstractFrontierService.java
Labels: bug, Server

#93 Add method ListURLs to list all URLs known in the frontier with their next fetch date
  API/src/main/java/crawlercommons/urlfrontier/URLFrontierGrpc.java
  API/src/main/java/crawlercommons/urlfrontier/Urlfrontier.java
  API/urlfrontier.proto
  client/src/main/java/crawlercommons/urlfrontier/client/Client.java
  client/src/main/java/crawlercommons/urlfrontier/client/ListURLs.java
  service/src/main/java/crawlercommons/urlfrontier/service/AbstractFrontierService.java
  service/src/main/java/crawlercommons/urlfrontier/service/ignite/IgniteService.java
  service/src/main/java/crawlercommons/urlfrontier/service/memory/MemoryFrontierService.java
  service/src/main/java/crawlercommons/urlfrontier/service/memory/URLQueue.java
  service/src/main/java/crawlercommons/urlfrontier/service/rocksdb/RocksDBService.java
  service/src/main/java/crawlercommons/urlfrontier/service/rocksdb/ShardedRocksDBService.java
  service/src/test/java/crawlercommons/urlfrontier/service/MemoryFrontierServiceTest.java
  service/src/test/java/crawlercommons/urlfrontier/service/RocksDBServiceTest.java
  service/src/test/java/crawlercommons/urlfrontier/service/ServiceTestUtil.java
Labels: enhancement, API, Client

#100 Remove Ignite, implements #96
  service/README.md
  service/config.ini
  service/pom.xml
  service/src/main/java/crawlercommons/urlfrontier/service/ignite/IgniteHeartbeat.java
  service/src/main/java/crawlercommons/urlfrontier/service/ignite/IgniteService.java
  service/src/main/java/crawlercommons/urlfrontier/service/ignite/Key.java
  service/src/main/java/crawlercommons/urlfrontier/service/ignite/Payload.java
Labels: Ignite

#103 Added myself in the developper list
  pom.xml
Labels: good first issue

#102 Better organisation of Maven plugins and update their version
  client/pom.xml
  pom.xml
  service/pom.xml
  tests/pom.xml
Labels: enhancement, dependencies

#105 Improved handling of dependencies and updated their versions
  API/pom.xml
  client/pom.xml
  pom.xml
  service/pom.xml
Labels: dependencies

#106 Reverted back to GRPC 1.66.0 and updated protoc to 3.25.5
  API/README.md
  API/pom.xml
  API/src/main/java/crawlercommons/urlfrontier/URLFrontierGrpc.java
  API/src/main/java/crawlercommons/urlfrontier/Urlfrontier.java
  client/pom.xml
  pom.xml
Labels: dependencies, Security

#107 Prerelease 2.4
  API/README.md
  client/src/main/java/crawlercommons/urlfrontier/client/Client.java
  service/src/main/java/crawlercommons/urlfrontier/service/URLFrontierServer.java
Labels: documentation
